project:
  type: book

book:
  title: "Executive Dashboard Documentation"
  author: "Starita Solutions"
  date: "5/6/2025"
  chapters:
    - index.qmd
    - data_sources.qmd
    - kpi_overview.qmd
    - crm.qmd
    - freedom.qmd
    - meevo.qmd
  sidebar:
    logo: www/SS_Logo_Black.png
    title: ""
    

number-depth: 2

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

